---
- name: Remove packages
  pip:
    name="{{ item }}"
    state=absent
    executable="{{ pip_packages_executable | default(omit, true) }}"
  with_items: "{{ pip_packages_remove }}"
  when: pip_packages_remove
